In [ ]:
import numpy as np

In [10]:
## 넘파이를 이용하여 배열 만들기
np.array([1,2,3,4])

## 0부터 5사이의 랜덤한 값이 담긴 3x5 array 만들어보기 
'''
np.random.randint(low, high=None, size=None, dtype=int)
low : 최소값(포함)
high : 최대값(제외)
size : (x,y) 생성할 배열의 shape , x행 y열
dtype : 자료형 int(기본)
'''
array = np.random.randint(0,5,(3,5))
array_f = np.random.uniform(0, 5, (3, 5))  # 0.0 이상 5.0 미만 실수 (실수로 만들고 싶다면 uniform)
print(array)
print(array_f)

[[4 3 2 2 2]
 [4 2 4 0 0]
 [0 2 1 2 1]]
[[1.63242827 1.24365824 4.94977079 3.52786846 2.83292658]
 [0.75407006 2.31461613 0.05096854 3.90057992 4.76568688]
 [0.12134387 4.76467984 4.48215183 3.70941867 0.51857638]]


In [20]:
## numpy 배열 생성함수 arange(n) - 0부터 n미만의 정수를 1씩 증가하면서 나열한 Numpy 배열
'''
np.arange([start,] stop[, step])
start : 시작값(포함, 생략시 0)
stop : 끝값(제외)
step : 증가단위 (생략시 1)
'''
np.arange(7)
target = np.arange(1,16,2)
print(target)

## 슬라이싱 결과가 3,5만 나오도록 하려면
print(target[1:3])
print(target[(target==3) | (target==5)])
print(target[np.isin(target, [3,5])])

[ 1  3  5  7  9 11 13 15]
[3 5]
[3 5]
[3 5]


In [31]:
print("1차원 array")
array = np.arange(10)
print(f"ㄴ자료형출력 : {type(array)}")
print(f"ㄴ차원출력 : {array.ndim}")
print(f"ㄴ모양출력 : {array.shape}")
print(f"ㄴ크기출력 : {array.size}")
print(f"ㄴdata type출력 : {array.dtype}")
print(f"ㄴ5번인덱스 요소 출력 : {array[5]}")
print(f"ㄴ3~5번인덱스 요소 출력 : {array[3:6]}")

1차원 array
ㄴ자료형출력 : <class 'numpy.ndarray'>
ㄴ차원출력 : 1
ㄴ모양출력 : (10,)
ㄴ크기출력 : 10
ㄴdata type출력 : int64
ㄴ5번인덱스 요소 출력 : 5
ㄴ3~5번인덱스 요소 출력 : [3 4 5]


In [38]:
print("2차원 array")
array = np.arange(1,16).reshape(3,5) # 1~15까지의 3행5열 배열 출력
print(array)
print(f"ㄴ자료형출력 : {type(array)}")
print(f"ㄴ차원출력 : {array.ndim}")
print(f"ㄴ모양출력 : {array.shape}")
print(f"ㄴ크기출력 : {array.size}")
print(f"ㄴdata type출력 : {array.dtype}")
print(f"ㄴmatrix의 2행3열 요소 출력 : {array[2,3]}")
print(f"ㄴ행은 0~1, 열은 1~3까지 출력 \n {array[0:2,1:3]}")

2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
ㄴ자료형출력 : <class 'numpy.ndarray'>
ㄴ차원출력 : 2
ㄴ모양출력 : (3, 5)
ㄴ크기출력 : 15
ㄴdata type출력 : int64
ㄴmatrix의 2행3열 요소 출력 : 14
ㄴ행은 0~1, 열은 1~3까지 출력 
 [[2 3]
 [7 8]]


In [41]:
# 주어진 array를 matrix라는 변수로 (2,4)모양으로 reshape 하여 저장하기
print("1차원")
arr = np.arange(8)
matrix = arr.reshape(2,4)
print(matrix)

1차원
[[0 1 2 3]
 [4 5 6 7]]


In [53]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(f"모양 : {matrix.shape}")
'''
np.concatenate((a1, a2, ...), axis=0)
(a1, a2, ...) : 붙일 배열, 튜플 또는 리스트로 전달
axis : 어떤 축을 따라 붙일지 결정 (기본값 = 0) / 
    axis=0 (y축) >> 행(row)기준처리 >> 아래로 붙이기 위아래로 합치기
    axis=1 (x축) >> 열(column)기준처리 >> 옆으로 붙이기 / 좌우로 합치기
'''
# matrix 변수 두개를 세로로 이어붙이고 m으로 출력
m = np.concatenate((matrix, matrix), axis=0)
print(f"\n {m}")
print(f"모양 : {m.shape}")

# matrix 변수 두개를 가로로 이어붙이고 n으로 출력
n = np.concatenate((matrix, matrix), axis=1)
print(f"\n {n}")
print(f"모양 : {n.shape}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
모양 : (3, 3)

 [[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
모양 : (6, 3)

 [[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]
모양 : (3, 6)


In [61]:
matrix = np.arange(16).reshape(4,4)
print(matrix, "\n")

# axis 0 을 활용하여 3번째 행을 기준으로 나누고 각각 a, b에 저장 
a, b = np.split(matrix, [3], axis=0)
print(a, "\n")
print(b, "\n")
# aixs 1 을 활용하여 1번째 열을 기준으로 나누고 각각 c, d에 저장 
c, d = np.split(matrix, [1], axis=1)
print(c, "\n")
print(d, "\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]] 

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]] 



In [63]:
x = np.arange(4)
print(x * 5)

[ 0  5 10 15]


In [76]:
print("Numpy 연산 확인")
array = np.arange(1,6)
print(array)
print(array+5)
print(array-5)
print(array*5)
print(array/5)
array2 = np.arange(5, 0, -1)
print(array2)
print(array+array2)
print(array-array2)


Numpy 연산 확인
[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[5 4 3 2 1]
[6 6 6 6 6]
[-4 -2  0  2  4]


In [81]:
A = np.arange(6).reshape(3,2)
print(A)
B = np.arange(3).reshape(3,1)
print(B)
print(A+B)

[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]]
[[0 1]
 [3 4]
 [6 7]]


In [82]:
A = np.arange(6).reshape(6,1)
B = np.arange(6)
print(A+B)

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


In [95]:
matrix = np.arange(8).reshape((2, 4))
print(matrix)

print(f"전체 합계 : {matrix.sum()}")
print(f"최대값 : {matrix.max()}")
print(f"최소값 : {matrix.min()}")
print(f"평균값 : {matrix.mean()}")
print(f"행별 합계 : {matrix.sum(axis=1)}")
print(f"열별 합계 : {matrix.sum(axis=0)}")
print(f"표준편차 : {matrix.std()}")
print(f"5보다 작은수만 출력 : {matrix[matrix<5]}")

[[0 1 2 3]
 [4 5 6 7]]
전체 합계 : 28
최대값 : 7
최소값 : 0
평균값 : 3.5
행별 합계 : [ 6 22]
열별 합계 : [ 4  6  8 10]
표준편차 : 2.29128784747792
5보다 작은수만 출력 : [0 1 2 3 4]


In [109]:
daily_liar_data = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]
# 0은 거짓말을 한 날이고, 1은 거짓말을 하지 않은 날이다. 양치기 소년이 100일 중거짓말을 총 몇번했는지 그 횟수를 세어 정확히 출력할것
arr = np.array(daily_liar_data)
'''
count_nonzero : 조건에 맞는 원소 개수 세는 함수

'''
print(np.count_nonzero(arr==0)) 
print(np.bincount(arr))
print(np.sum(arr==0))
print(len(arr[arr==0]))
print(100-arr.sum())

71
[71 29]
71
71
71
